- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Restart sshd
  service:
    name: ssh
    state: restarted
  when: ansible_distribution == 'Ubuntu'