- name: Reload sysctl config
  command: sysctl -p

- name: Restart keepalived service
  service:
    name: keepalived
    state: restarted

- name: Restart firewall config
  ansible.builtin.service:
    name: firewalld
    state: reloaded