---
# molecule/default/converge.yml
- name: Configure and Test Dual-Host Setup
  hosts: all
  remote_user: vagrant
  become: true
  serial: 1
  roles:
    - stop_keepalived
    - bootstrap
    - updates
    - sshd
    - keepalived
    - docker
    - pihole
    - start_keepalived