- name: Stop and disable resolver
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Restart network
  service:
    name: network
    state: restarted