- name: Install sqlite3
  apt:
    force_apt_get: true
    name: sqlite3
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install sqlite3 CentOS
  yum:
    name:
      - sqlite
      - rsync
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create gravity sync configuration folder
  ansible.builtin.file:
    path: /etc/gravity-sync/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  register: sync_dir

- name: Create gravity sync log folder
  ansible.builtin.file:
    path: /var/log/gravity-sync/
    state: directory
    owner: "root"
    group: "root"
  register: sync_log_dir

- name: Generate ssh keypair
  community.crypto.openssh_keypair:
    comment: pihole-sync-{{ inventory_hostname }}
    path: "{{ sync_dir.path }}/gravity-sync.rsa"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  register: ssh_key

- name: Create known host file
  ansible.builtin.file:
    path: "{{ ansible_user_home_dir }}/.ssh/known_hosts"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    state: touch
  register: known_hosts

- name: Ensure servers are present in known_hosts file
  known_hosts:
    name: "{{ hostvars[item].ansible_host }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
    hash_host: true
    path: "{{ known_hosts.dest }}"
  with_items: "{{ groups['all']|difference([inventory_hostname]) }}"

- name: Add key to authorized_keys on all other nodes
  ansible.posix.authorized_key:
    key: "{{ ssh_key.public_key }}"
    user: "{{ ansible_user }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['all']|difference([inventory_hostname]) }}"

- name: Git checkout gravity-sync
  ansible.builtin.git:
    repo: 'https://github.com/vmstan/gravity-sync.git'
    dest: '{{ sync_dir.path }}.gs'
    version: "{{ gravity_sync_version }}"

- name: Move program to correct location
  ansible.builtin.copy:
    src: '{{ sync_dir.path }}.gs/gravity-sync'
    dest: "/usr/local/bin/gravity-sync"
    remote_src: yes
    mode: 0755

- set_fact:
    peerip_addr: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | difference(ansible_host) | list }}"
  run_once: true

- name: Copy sync script
  template:
    dest: /tmp/gravity-sync.conf
    src: gravity-sync.j2
    mode: 0644

- name: Remove ansible junk from gravity config file & put into correct place
  ansible.builtin.shell: cat /tmp/gravity-sync.conf | sed 's/[][]//g' | sed "s/['\]//g" > "{{ sync_dir.path }}/gravity-sync.conf"

- name: start auto sync for gravity
  ansible.builtin.shell: gravity-sync auto > /dev/null 2>&1
  async: 60
  poll: 5
