- name: Install sqlite3
  apt:
    force_apt_get: true
    name: sqlite3
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install sqlite3 CentOS
  yum:
    name:
      - sqlite
      - rsync
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create gravity sync folder
  ansible.builtin.file:
    path: /etc/gravity-sync/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  register: sync_dir

- name: Create gravity sync folder
  ansible.builtin.file:
    path: /var/log/gravity-sync/
    state: directory
    owner: "root"
    group: "root"
  register: sync_log_dir

- name: Git checkout gravity-sync
  ansible.builtin.git:
    repo: 'https://github.com/vmstan/gravity-sync.git'
    dest: '{{ sync_dir.path }}.gs'
    version: "{{ gravity_sync_version }}"

- name: Move program to correct location
  ansible.builtin.copy:
    src: '{{ sync_dir.path }}.gs/gravity-sync'
    dest: "/usr/local/bin/gravity-sync"
    remote_src: yes
    mode: 0755

- set_fact:
    peerip_addr: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | difference(ansible_host) | list }}"
  run_once: true

- name: Copy sync script
  template:
    dest: "{{ sync_dir.path }}/gravity-sync.conf"
    src: gravity-sync.j2
    mode: 0644

# add the program executable to the correct path
# add the configuration file to the folder
