- name: Install sqlite3
  apt:
    force_apt_get: true
    name: sqlite3
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install sqlite3 CentOS
  yum:
    name:
      - sqlite
      - rsync
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Generate ssh keypair
  community.crypto.openssh_keypair:
    comment: pihole-sync-{{ inventory_hostname }}
    path: '{{ ansible_user_dir }}/.ssh/id_rsa_sync'
  register: ssh_key

- name: Add key to authorized_keys on all other nodes
  ansible.posix.authorized_key:
    key: "{{ ssh_key.public_key }}"
    user: "{{ ansible_user }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] | difference([inventory_hostname]) }}"

- name: Create sync folder
  file:
    path: pihole_sync
    state: directory
    mode: 0755
  register: sync_dir

- name: Copy sync script
  template:
    dest: "{{ sync_dir.path }}/pihole_sync.sh"
    src: pihole_sync.j2
    mode: 0755

- name: Schedule sync with cron
  ansible.builtin.cron:
    hour: "*"
    minute: "0"
    job: "/home/{{ ansible_user }}/{{ sync_dir.path }}/pihole_sync.sh"
    user: root
    name: pihole-sync
