- name: Set correct handeler for Redhat Family
  set_fact:
    ssh_service: Restart sshd
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set correct handeler for OS Ubuntu
  set_fact:
    ssh_service: Restart ssh
  when: ansible_distribution == 'Ubuntu'

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "MaxSessions", value: "5" }
    - { key: "MaxAuthTries", value: "3" }
  notify:
    - "{{ ssh_service }}"

- name: Flush handlers
  meta: flush_handlers
