
- name: Install Python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Ensure firwewalld is installed
  ansible.builtin.apt:
    name: firewalld
    state: present
  become: true
  when: firewall_deploy | lower == 'true'