---
# Main task file for Pi-hole setup using Ansible
- name: Debian setup tasks
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Redhat setup tasks
  include_tasks: redhat.yml  
  when: ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Run pre-deployment tasks
  include_tasks: pre.yml

- name: Deploy Pi-hole container
  include_tasks: deploypi.yml

- name: Configure firewall
  include_tasks: firewall.yml
  when: firewall_deploy | lower == 'true'

- name: Verify Pi-hole deployment
  include_tasks: verify.yml
