---
- name: Install python3 pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install python-requests
  ansible.builtin.dnf:
    name: python-requests
    state: present

- name: Install firewalls
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when: firewall_deploy | lower == 'true'