---
- name: Check if Pi-hole container is running
  command: docker ps --filter "name=pihole" --filter "status=running"
  register: container_status

- name: Fail if Pi-hole container is not running
  fail:
    msg: "Pi-hole container is not running."
  when: container_status.stdout_lines | length == 0

- name: Test DNS Resolution
  command: dig +short @127.0.0.1 google.com
  register: dns_test
  failed_when: dns_test.stdout == ""

- name: Assert DNS Resolution is Working for Multiple IPs
  assert:
    that:
      - dns_test.stdout | regex_search('216\\.58\\.|172\\.217\\.|142\\.250\\.')

- name: INFORMATION
  debug:
    msg:
      - "In the {{ execution_mode }} make sure to point your DNS server settings here:"
      - "DNSv4: {{ pihole_local_ipv4 }}"
      - "DNSv6: {{ pihole_local_ipv6 }}"
