---
- name: Check if Pi-hole container is running
  command: docker ps --filter "name=pihole" --filter "status=running"
  register: container_status

- name: Fail if Pi-hole container is not running
  fail:
    msg: "Pi-hole container is not running."
  when: container_status.stdout_lines | length == 0

- name: Verify DNS resolution through Pi-hole
  command: nslookup google.com 127.0.0.1
  register: dns_test

- name: Fail if DNS resolution test fails
  fail:
    msg: "DNS resolution through Pi-hole failed: {{ dns_test.stderr }}"
  when: dns_test.rc != 0

- name: INFORMATION
  debug:
    msg:
      - "In the {{ execution_mode }} make sure to point your DNS server settings here:"
      - "DNSv4: {{ pihole_local_ipv4 }}"
      - "DNSv6: {{ pihole_local_ipv6 }}"
